spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://lending.cscg6f0frodu.us-east-1.rds.amazonaws.com/lending?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: lending
      password: qwer1234

  jpa:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show_sql: true
    format_sql: true

---
spring:
  application:
    name: cloudlibrary-lending-local
  config:
    activate:
      on-profile: local

---
spring:
  application:
    name: cloudlibrary-lending-dev
  config:
    activate:
      on-profile: dev

---
spring:
  application:
    name: cloudlibrary-lending-prod
  config:
    activate:
      on-profile: prod