spring:
  profiles:
    active: local


---
spring:
  application:
    name: cloudlibrary-lending-local
  config:
    activate:
      on-profile: local

---
spring:
  application:
    name: cloudlibrary-lending-dev
  config:
    activate:
      on-profile: dev

---
spring:
  application:
    name: cloudlibrary-lending-prod
  config:
    activate:
      on-profile: prod